    

    var swedishColors = {
            aliceblue: 'f0f8ff',
            antiquewhite: 'faebd7',
            aqua: '00ffff',
            akvamarin: '7fffd4',
            azure: 'f0ffff',
            beige: 'f5f5dc',
            bisque: 'ffe4c4',
            svart: '000000',
            blanchedalmond: 'ffebcd',
            blå: '0000ff',
            blueviolet: '8a2be2',
            brun: 'a52a2a',
            burlywood: 'deb887',
            cadetblue: '5f9ea0',
            Chartreuse: '7fff00',
            choklad: 'd2691e',
            korall: 'ff7f50',
            cornflowerblue: '6495ed',
            cornsilk: 'fff8dc',
            crimson: 'dc143c',
            cyan: '00ffff',
            mörkblå: '00008b',
            mörkcyan: '008b8b',
            mörkgoldenrod: 'b8860b',
            mörkgrå: 'a9a9a9',
            mörkgrön: '006400',
            mörkkhaki: 'bdb76b',
            mörkmagenta: '8b008b',
            mörkolivegreen: '556b2f',
            mörkorange: 'ff8c00',
            mörkorchid: '9932cc',
            Mörkröd: '8b0000',
            mörksalmon: 'e9967a',
            mörkseagreen: '8fbc8f',
            mörkslateblue: '483d8b',
            mörkslategray: '2f4f4f',
            mörkturquoise: '00ced1',
            mörkviolet: '9400d3',
            deeppink: 'ff1493',
            deepskyblue: '00bfff',
            dimgray: '696969',
            dodgerblue: '1e90ff',
            fältspat: 'd19275',
            tegel: 'b22222',
            floralwhite: 'fffaf0',
            forestgreen: '228b22',
            fuchsia: 'ff00ff',
            Gainsboro: 'dcdcdc',
            ghostwhite: 'f8f8ff',
            guld: 'ffd700',
            gullris: 'daa520',
            grå: '808080',
            grön: '008000',
            greenyellow: 'adff2f',
            honungsdagg: 'f0fff0',
            hotpink: 'ff69b4',
            indianred: 'cd5c5c',
            indigo: '4b0082',
            elfenben: 'fffff0',
            khaki: 'f0e68c',
            lavendel: 'e6e6fa',
            lavenderblush: 'fff0f5',
            lawngreen: '7cfc00',
            lemonchiffon: 'fffacd',
            ljusblå: 'add8e6',
            lightcoral: 'f08080',
            lightcyan: 'e0ffff',
            lightgoldenrodyellow: 'fafad2',
            ljusgrå: 'd3d3d3',
            ljusgrön: '90ee90',
            ljusrosa: 'ffb6c1',
            lightsalmon: 'ffa07a',
            lightseagreen: '20b2aa',
            lightskyblue: '87cefa',
            lightslateblue: '8470ff',
            lightslategray: '778899',
            lightsteelblue: 'b0c4de',
            lightyellow: 'ffffe0',
            lime: '00ff00',
            limegrön: '32cd32',
            linne: 'faf0e6',
            magenta: 'ff00ff',
            rödbrun: '800000',
            mediumaquamarine: '66cdaa',
            mediumblue: '0000cd',
            mediumorchid: 'ba55d3',
            mediumpurple: '9370d8',
            mediumseagreen: '3cb371',
            mediumslateblue: '7b68ee',
            mediumspringgreen: '00fa9a',
            mediumturquoise: '48d1cc',
            mediumvioletred: 'c71585',
            midnightblue: '191970',
            mintcream: 'f5fffa',
            mistyrose: 'ffe4e1',
            mockasin: 'ffe4b5',
            navajowhite: 'ffdead',
            marinblå: '000080',
            oldlace: 'fdf5e6',
            oliv: '808000',
            olivedrab: '6b8e23',
            apelsin: 'ffa500',
            orangeröda: 'ff4500',
            orchid: 'da70d6',
            palegoldenrod: 'eee8aa',
            palegreen: '98fb98',
            paleturquoise: 'afeeee',
            palevioletred: 'd87093',
            papayawhip: 'ffefd5',
            peachpuff: 'ffdab9',
            peru: 'cd853f',
            rosa: 'ffc0cb',
            plommon: 'dda0dd',
            powderblue: 'b0e0e6',
            purpur: '800080',
            röd: 'ff0000',
            rosybrown: 'bc8f8f',
            royalblue: '4169e1',
            saddlebrown: '8b4513',
            lax: 'fa8072',
            sandbrun: 'f4a460',
            sjögrön: '2e8b57',
            snäcka: 'fff5ee',
            sienna: 'a0522d',
            silver: 'c0c0c0',
            himmelsblå: '87ceeb',
            slateblue: '6a5acd',
            slategray: '708090',
            snö: 'fffafa',
            springgreen: '00ff7f',
            steelblue: '4682b4',
            tan: 'd2b48c',
            blågrön: '008080',
            tistel: 'd8bfd8',
            tomat: 'ff6347',
            turkos: '40e0d0',
            violett: 'ee82ee',
            violetred: 'd02090',
            vete: 'f5deb3',
            vit: 'ffffff',
            vitrök: 'f5f5f5',
            gul: 'ffff00',
            gulgrön: '9acd32'
    };

    module.exports = function(swedishName)
    {
        var hex2rgb = function(hex) {

          if (hex[0]=="#") hex=hex.substr(1);
          var r = hex.substring(0, 2);
          var g = hex.substring(2, 2);
          var b = hex.substring(4, 2);

          return {
            red:   parseInt(r,16),
            green: parseInt(g,16),
            blue:  parseInt(b,16),
            hex: hex
          }
        }
        
        var hex = swedishColors[swedishName];
        if (!hex)
                return null;

        var color = hex2rgb(hex);
        if (!color)
                console.log('didn\'t find color ' + color);

        return color;
    }

